function makefigs(output::Symbol, font::String, scale::Float64)
  #fig00_1(output, font, scale)
  fig02_1(output, font, scale)
  fig03_1(output, font, scale)
  fig04_1(output, font, scale)
  fig04_2(output, font, scale)
  fig04_3(output, font, scale)
  fig04_4(output, font, scale)
  fig05_1(output, font, scale)
  fig05_2(output, font, scale)
  fig06_1(output, font, scale)
  fig07_1(output, font, scale)
  fig10_1(output, font, scale)
  fig10_2(output, font, scale)
  fig10_3(output, font, scale)
  fig10_4(output, font, scale)
  fig10_5(output, font, scale)
  fig11_1(output, font, scale)
  fig11_2(output, font, scale)
  fig12_1(output, font, scale)
  fig12_2(output, font, scale)
  fig15_1(output, font, scale)
  fig15_2(output, font, scale)
  fig16_1(output, font, scale)
  fig18_1(output, font, scale)
  fig19_1(output, font, scale)
end