[[chap19]]
== The Goodies: Syntax

One of my goals for this book has been to teach you as little Julia as possible. When there were two ways to do something, I picked one and avoided mentioning the other. Or sometimes I put the second one into an exercise.

Now I want to go back for some of the good bits that got left behind. Julia provides a number of features that are not really necessary—you can write good code without them—but with them you can sometimes write code that’s more concise, readable or efficient, and sometimes all three.

This chapter and the two following discuss the things I have left out in the previous chapters: 

* syntax supplements
* functions, types and macros directly available in +Base+
* functions, types and macros in the Standard Library

Credit: this chapter is a synthesis of the corresponding parts in the offical Julia documentation: https://docs.julialang.org

=== Functions

==== Named Tuples

==== Keyword Arguments

==== +do+ Block

=== Control Flow

==== Ternary Operator

==== Short-Circuit Evaluation

==== Tasks

=== Types

==== Primitive Types

==== Type Unions

==== Parametric Types

=== Methods

==== Parametric Methods

==== Parametric Constructors

=== Metaprogramming

=== Missing Values

=== Calling C and Fortran Code

=== Glossary

Regex::